hl.workspace_rule({ workspace = 1, default_name = "一", monitor = "eDP-1" })
hl.workspace_rule({ workspace = 2, default_name = "二", monitor = "DP-1" })
hl.workspace_rule({ workspace = 2, default_name = "二", monitor = "DP-2" })
hl.workspace_rule({ workspace = 3, default_name = "三", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = 4, default_name = "四" })
hl.workspace_rule({ workspace = 5, default_name = "五" })
hl.workspace_rule({ workspace = 6, default_name = "六" })
hl.workspace_rule({ workspace = 7, default_name = "七" })
hl.workspace_rule({ workspace = 8, default_name = "八" })
hl.workspace_rule({ workspace = 9, default_name = "九" })
hl.workspace_rule({ workspace = 10, default_name = "十" })
