hl.bind('XF86AudioPlay', hl.dsp.exec_cmd('playerctl play-pause'), { locked = true })
hl.bind('XF86AudioNext', hl.dsp.exec_cmd('playerctl next'), { locked = true })
hl.bind('XF86AudioPrev', hl.dsp.exec_cmd('playerctl previous'), { locked = true })

hl.bind('XF86AudioRaiseVolume', hl.dsp.exec_cmd('volume increase sink'), { repeating = true })
hl.bind('XF86AudioLowerVolume', hl.dsp.exec_cmd('volume decrease sink'), { repeating = true })
hl.bind('XF86AudioMute', hl.dsp.exec_cmd('volume mute sink toggle'))
hl.bind('SHIFT + XF86AudioRaiseVolume', hl.dsp.exec_cmd('volume increase sink 20'), { repeating = true })
hl.bind('SHIFT + XF86AudioLowerVolume', hl.dsp.exec_cmd('volume decrease sink 20'), { repeating = true })
hl.bind('CONTROL + XF86AudioRaiseVolume', hl.dsp.exec_cmd('volume set sink 100'), { repeating = false })
hl.bind('CONTROL + XF86AudioLowerVOlume', hl.dsp.exec_cmd('volume set sink 50'), { repeating = false })

hl.bind('Print', hl.dsp.exec_cmd(HYPR.paths.bin .. '/screenshot.sh monitor both'))
hl.bind('CONTROL + Print', hl.dsp.exec_cmd(HYPR.paths.bin .. '/screenshot.sh full both'))
hl.bind('ALT + Print', hl.dsp.exec_cmd(HYPR.paths.bin .. '/screenshot.sh window both'))
hl.bind('SHIFT + Print', hl.dsp.exec_cmd(HYPR.paths.bin .. '/screenshot.sh region both'))
