#!/usr/bin/zsh

DEVICE_ID=`xinput list | awk -F "=" '/Synaptics/ { print $2 }' | awk '{ print $1 }'`

STATUS=`xinput list-props $DEVICE_ID | awk -F : '/Device Enabled/ { print $2 }'`

new_status=$(( 1 - $STATUS ))

sudo xinput set-prop $DEVICE_ID "Device Enabled" $new_status

