#!/bin/zsh

function current_volume() {
  echo $(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{ print $5 }' | rev | cut -c2- | rev)
}

function current_mute_state() {
  echo $(pactl get-sink-mute @DEFAULT_SINK@ | awk '{ print $2 }')
}

function is_muted() {
  [ $1 = "yes" -o $1 = "on" ]
}

function update_volume_icon() {
  [ -z $1 ] && volume=$(current_volume) || volume=$1
  [ -z $2 ] && muted=$(current_mute_state) || muted=$2

  if is_muted $muted; then
    icon="muted"
  elif [ $volume -eq 0 ]; then
    icon="off"
  elif [ $volume -lt 40 ]; then
    icon="low"
  elif [ $volume -lt 70 ]; then
    icon="medium"
  else
    icon="high"
  fi

  eww update volume=$volume
  eww update volume-icon="$icon"

  notify_volume $volume $muted
}

function notify_volume() {
  previous_notification_id=$(eww get volume-notification-id)

  [ -z $previous_notification_id ] && previous_notification_id=0
  [ -z $1 ] && volume=$(current_volume) || volume=$1
  [ -z $2 ] && muted=$(current_mute_state) || muted=$2

  message="Volume set to: $volume%"

  is_muted $muted && message="$message (muted)"

  notification_id=$(notify-send -r $previous_notification_id -p $message)

  eww update volume-notification-id=$notification_id
}

case $1 in
  set)
    pactl set-sink-volume @DEFAULT_SINK@ $2%
    update_volume_icon $2
  ;;

  mute)
    pactl set-sink-mute @DEFAULT_SINK@ $2
    update_volume_icon
  ;;
esac
