function load(filepath)
  dofile('/home/hikari/.config/hypr/hyprland.d/' .. filepath .. '.lua')
end

load('vars')
load('env')
load('monitors')
load('hypr-config')
load('animations')
load('workspaces')
load('windows')
load('startup')
load('events/init')
load('bindings/system')
load('bindings/apps')
load('bindings/multimedia')
load('bindings/hyprland')
load('layouts/' .. HYPR.layout)
