# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

envd = GBM_BACKEND,nvidia-drm
envd = LIBVA_DRIVER_NAME,nvidia
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia

env  = WLR_NO_HARDWARE_CURSORS,1

